config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :calls, only: [:create, :show, :index, :new, :edit, :update]
  resources :computers

  devise_for :users, path: "/", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'secret', 
    confirmation: 'verificacao', unlock: 'desbloquear', registration: 'resgistro', sign_up: 'criar' }
  
  root "pages#index"
  
  get "/sistema" => "system#index"
  
  namespace :admin do 
    root "pages#index"
    get "/contrato" => "pages#contract"
    get "/relatorios"=> "pages#relatorio"
    resources :calls
    resources :computers
    resources :services

  end
end

app/models/computer.rb
class Computer < ActiveRecord::Base
  belongs_to :user
  has_many :calls

  validates :name , presence: true
  validates :model, presence: true
  validates :user_id, presence: true
  validates :cpu, presence: true
  validates :ram, presence: true
  validates :hd, presence: true
  validates :brand, presence: true
  validates :operation_system ,presence: true
  validates :video_card, presence: true

end

app/controllers/admin/computers_controller.rb
class Admin::ComputersController < AdminController
  before_action :set_admin_computer, only: [:show, :edit, :update, :destroy]

  # GET /admin/computers
  # GET /admin/computers.json
  def index
    @admin_computers = Computer.all
  end

  # GET /admin/computers/1
  # GET /admin/computers/1.json
  def show
  end

  # GET /admin/computers/new
  def new
    @admin_computer = Computer.new
  end

  # GET /admin/computers/1/edit
  def edit
  end

  # POST /admin/computers
  # POST /admin/computers.json
  def create
    @admin_computer = Computer.new(admin_computer_params)

    respond_to do |format|
      if @admin_computer.save
        format.html { redirect_to @admin_computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @admin_computer }
      else
        format.html { render :new }
        format.json { render json: @admin_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/computers/1
  # PATCH/PUT /admin/computers/1.json
  def update
    respond_to do |format|
      if @admin_computer.update(admin_computer_params)
        format.html { redirect_to @admin_computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_computer }
      else
        format.html { render :edit }
        format.json { render json: @admin_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/computers/1
  # DELETE /admin/computers/1.json
  def destroy
    @admin_computer.destroy
    respond_to do |format|
      format.html { redirect_to admin_computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_computer
      @admin_computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_computer_params
      params.fetch(:admin_computer, {})
    end
end

app/controllers/computers_controller.rb
class ComputersController < SystemController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)
    @computer.user = current_user
    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computador cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: "Computador atualizado com sucesso" }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit!
    end
end

app/helpers/admin/computers_helper.rb
module Admin::ComputersHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= simple_form_for(@computer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="col-lg-4 col-md-4">
      <%= f.input :name,label: "Nome do computador",placeholder: "ex: Notebook Dell" %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :cpu,label: "Processador",prompt: "Qual a cpu?" ,collection: ["Intel Atom", "Intel Dual Core", "Intel Core2Duo", "Intel Core2Quad","Intel Core i3","Intel Core i5", "Intel Core i7", "Outro"]  %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :model,label: "Tipo de Computador", as: :select,prompt: "Escolha um tipo" ,collection: ["Desktop","Notebook"] %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :ram , as: :select, prompt: "Memória ram", collection: ["512 MB","1 GB","2 GB","3 GB","4 GB","6 GB","8GB","16 GB","32 GB", "Outro"] %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :brand, label: "Marca",prompt: "Escolha uma marca", collection: ["Dell","LG","Asus","Apple","Acer","Itautec","Samsumg", "Outro"].sort %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :video_card, label: "Placa de Video",prompt: "Possui Placa?", collection: ["sim", "nao"] %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :hd,prompt: "Quantos GB?" ,collection: ["80 GB","160 GB", "320 GB","500 GB","1 TB","2 TB","Outro"] %>
    </div>

    <div class="col-lg-4 col-md-4">
      <%= f.input :operation_system,prompt: "Sistema" ,label: "Sistema Operacional", collection: ["Windows", "Mac OSX", "Linux", "Dual Boot"] %>
    </div>    
  
  </div>

  <div class="form-actions col-lg-12 col-md-12">
    <%= link_to 'Voltar', computers_path, class: "btn btn-warning" %>
    <%= f.button :submit, "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<div class="intro-lead-in">
	<div class="text-muted">Editar Computador</div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<div class="text-muted intro-lead-in">Meus Computadores</div>

    <% current_user.computers.each do |computer| %>
      <div class="col-lg-4 col-md-6">
          <div class="panel panel-danger">
              <div class="panel-heading">
                  <div class="row">
                      <div class="col-xs-3">
                          <i class="fa fa-laptop fa-5x"></i>
                      </div>
                      <div class="col-xs-9 text-right">
                          <div>NOME: <%= computer.name %></div>
                          <div>CPU: <%= computer.cpu %></div>
                          <div>RAM: <%= computer.ram %> GB</div>
                          <div>HD: <%= computer.hd %> GB</div>
                      </div>
                  </div>
              </div>

              <%= link_to computer  do %>
                  <div class="panel-footer">
                      <span class="pull-left">Ver Detalhes</span>
                      <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                      <div class="clearfix"></div>
                  </div>
              <% end -%>
          </div>
          <%= link_to 'Editar', edit_computer_path(computer), class: "btn btn-info btn-xs" %>
          <%= link_to 'Deletar', computer, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger btn-xs" %>
      </div>
    <% end %>
    
    <% if current_user.computers.count  == 0 %>
      <p>
       <i class="text-muted">Você ainda não tem nenhum computador cadastrado</i>
      </p>
    <% end -%>
    <div class="col-lg-12 col-md-12">
      <hr>
    </div>
  <div class="col-lg-12 col-md-12">
    <%= link_to 'Cadastrar novo computador?', new_computer_path, class: "btn btn-primary " %>
  </div>

app/views/computers/new.html.erb
<div class="intro-lead-in">
	<div class="text-muted">Cadastrar computador</div>
</div>

<%= render 'form' %>

app/views/computers/show.html.erb
<div class="intro-lead-in">
  <div class="text-muted">
    <%= @computer.name %>
  </div>
</div>

<hr>
<p>
  <strong>Processador:</strong>
  <%= @computer.cpu %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @computer.model %>
</p>

<p>
  <strong>Memória RAM:</strong>
  <%= @computer.ram %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @computer.brand %>
</p>

<p>
  <strong>HD:</strong>
  <%= @computer.hd %>
</p>

<p>
  <strong>Placa de Vídeo:</strong>
  <%= @computer.video_card %>
</p>

<p>
  <strong>Sistema Operacional:</strong>
  <%= @computer.operation_system %>
</p>

<%= link_to 'Editar Computador', edit_computer_path(@computer),class: "btn btn-info btn-xs" %> |
<%= link_to 'Voltar', computers_path,class: "btn btn-warning btn-xs" %> |
<%= link_to "Suporte para esse PC", "",class: "btn btn-primary btn-xs" %>