config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :calls, only: [:create, :show, :index, :new, :edit, :update]
  resources :computers

  devise_for :users, path: "/", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'secret', 
    confirmation: 'verificacao', unlock: 'desbloquear', registration: 'resgistro', sign_up: 'criar' }
  
  root "pages#index"
  
  get "/sistema" => "system#index"
  
  namespace :admin do 
    root "pages#index"
    get "/contrato" => "pages#contract"
    get "/relatorios"=> "pages#relatorio"
    resources :calls
    resources :computers
    resources :services

  end
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :user
  belongs_to :computer

  validates :computer_id, presence: true
  validates :description, presence: true
end

app/controllers/admin/calls_controller.rb
class Admin::CallsController < AdminController
  layout "admin"
  before_action :set_admin_call, only: [:show, :edit, :update, :destroy]

  # GET /admin/calls
  # GET /admin/calls.json
  def index
    @admin_calls = Call.all
  end

  # GET /admin/calls/1
  # GET /admin/calls/1.json
  def show
  end

  # GET /admin/calls/new
  def new
    @admin_call = Call.new
  end

  # GET /admin/calls/1/edit
  def edit
  end

  # POST /admin/calls
  # POST /admin/calls.json
  def create
    @admin_call = Call.new(admin_call_params)

    respond_to do |format|
      if @admin_call.save
        format.html { redirect_to @admin_call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @admin_call }
      else
        format.html { render :new }
        format.json { render json: @admin_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/calls/1
  # PATCH/PUT /admin/calls/1.json
  def update
    respond_to do |format|
      if @admin_call.update(admin_call_params)
        format.html { redirect_to @admin_call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_call }
      else
        format.html { render :edit }
        format.json { render json: @admin_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/calls/1
  # DELETE /admin/calls/1.json
  def destroy
    @admin_call.destroy
    respond_to do |format|
      format.html { redirect_to admin_calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_call
      @admin_call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_call_params
      params.fetch(:admin_call, {})
    end
end

app/controllers/calls_controller.rb
class CallsController < SystemController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)
    @call.user = current_user
    @call.protocolo = rand 10000..99999
    @call.total = call_params[:services]

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Chamado criado com sucesso, logo entraremos em contato' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to admin_calls_path, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit!
    end
end

app/helpers/admin/calls_helper.rb
module Admin::CallsHelper
		def formatted_date
			hours = DateTime.now.hour
			minutes = DateTime.now.minute
			day = DateTime.now.day
			month = DateTime.now.month
			year = DateTime.now.year

			return "#{day}/#{month}/#{year} , #{hours}:#{minutes}"
		end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
  <% if has_computer? %>
    <%= simple_form_for(@call) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :computer_id,label: "Computador" ,collection: current_user.computers %>
        <%= f.input :description, label: "Descreva o Problema", hint: "Lembre-se, quanto maior a descrição do problema, mais rápido poderemos resolve-lo para você." %>
        
      </div>

      <div class="form-actions">
        <%= f.button :submit,"Confirmar Pedido", class: "btn btn-primary" %>
        <%= link_to 'VOLTAR', calls_path, class: "btn btn-warning " %>
      </div>
    <% end %>
  <% end -%>

app/views/calls/edit.html.erb
<div class="intro-lead-in">
	<div class="text-muted">Editar Chamados</div>
</div>
<%= render 'form' %>

app/views/calls/index.html.erb
<div class="intro-lead-in">
  <div class="text-muted">
    Todos os Chamados
  </div>
</div>
<% if current_user.calls.each.count > 0 %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Computador</th>
        <th>Protocolo</th>
        <th>Descrição</th>
        <th>Total</th>
        <th>Status</th>
        <th colspan="3">Opções</th>
      </tr>
    </thead>

    <tbody>
      <% @calls.each do |call| %>
        <tr>
          <td><%= call.computer.name %></td>
          <td><%= call.protocolo %></td>
          <td><%= call.description[0..100] %> ...</td>
          <td><%= call.total %></td>
          <% if call.status == nil -%>
            <td ><span class="label label-warning"><i>Em Andamento</i></span></td>
          <% else -%>
            <td ><span class="label label-success"><i>Completo</i></span></td>
          <% end -%>


          <td><%= link_to 'Mostrar', call, class: "btn btn-info btn-xs" %></td>
          <td><%= link_to 'Editar', edit_call_path(call), class: "btn btn-warning btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    <i class="text-muted">Você ainda não tem fez chamado, está com problemas? Clique no botão abaixo e nos contate.</i>
  </p>
<% end -%> 

<br>

<%= link_to 'Novo Chamado', new_call_path, class: "btn btn-primary" %>

app/views/calls/new.html.erb
<div class="intro-lead-in text-muted">
	Pedido de Suporte
</div>

<% if has_computer? %>

	<%= render 'form' %>
	<h4><span class="pull-right">Valor Total R$<span id="#call_total"> 00,00</span> </span></h4>

<% else -%>
	<p class="text-muted">
		<i>
			Você ainda não possui nenhum computador cadastrado, por favor, clique abaixo e cadastre um.
		</i>
	</p>
	<hr>
	<%= link_to "Cadastrar computador", new_computer_path, class: "btn btn-primary" %>
<% end -%>

app/views/calls/show.html.erb
<p>
  <strong>Úsuário:</strong>
  <%= @call.user.name %>
</p>

<p>
  <strong>Computador:</strong>
  <%= @call.computer.name %>
</p>

<p>
  <strong>Nº de protocolo:</strong>
  <%= @call.protocolo %>
</p>

<p>
  <strong>Serviços:</strong>
  <%= @call.service_id  %>
    
</p>

<p>
  <strong>Valor Total:</strong>
  <%= @call.total %>
</p>

<p>
  <strong>Descrição do problema:</strong>
  <%= @call.description %>
</p>


<p>
  <strong>Status:</strong>
  <% if @call.status == nil  %>
    <span class="label label-warning">Em andamento</span>
  <% else %>
    <span class="label label-success">Completo</span>
  <% end -%>
</p>

<p>
  Criado em 
  <%= @call.created_at.to_date %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>