config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :calls, only: [:create, :show, :index, :new, :edit, :update]
  resources :computers

  devise_for :users, path: "/", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'secret', 
    confirmation: 'verificacao', unlock: 'desbloquear', registration: 'resgistro', sign_up: 'criar' }
  
  root "pages#index"
  
  get "/sistema" => "system#index"
  
  namespace :admin do 
    root "pages#index"
    get "/contrato" => "pages#contract"
    get "/relatorios"=> "pages#relatorio"
    resources :calls
    resources :computers
    resources :services

  end
end

app/models/computer.rb
class Computer < ActiveRecord::Base
  belongs_to :user
  has_many :calls

  validates :name , presence: true
  validates :model, presence: true
  validates :user_id, presence: true
  validates :cpu, presence: true
  validates :ram, presence: true
  validates :hd, presence: true
  validates :brand, presence: true
  validates :operation_system ,presence: true
  validates :video_card, presence: true

end

app/controllers/admin/computers_controller.rb
class Admin::ComputersController < AdminController
  before_action :set_admin_computer, only: [:show, :edit, :update, :destroy]

  # GET /admin/computers
  # GET /admin/computers.json
  def index
    @admin_computers = Computer.all
  end

  # GET /admin/computers/1
  # GET /admin/computers/1.json
  def show
  end

  # GET /admin/computers/new
  def new
    @admin_computer = Computer.new
  end

  # GET /admin/computers/1/edit
  def edit
  end

  # POST /admin/computers
  # POST /admin/computers.json
  def create
    @admin_computer = Computer.new(admin_computer_params)

    respond_to do |format|
      if @admin_computer.save
        format.html { redirect_to @admin_computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @admin_computer }
      else
        format.html { render :new }
        format.json { render json: @admin_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/computers/1
  # PATCH/PUT /admin/computers/1.json
  def update
    respond_to do |format|
      if @admin_computer.update(admin_computer_params)
        format.html { redirect_to @admin_computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_computer }
      else
        format.html { render :edit }
        format.json { render json: @admin_computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/computers/1
  # DELETE /admin/computers/1.json
  def destroy
    @admin_computer.destroy
    respond_to do |format|
      format.html { redirect_to admin_computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_computer
      @admin_computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_computer_params
      params.fetch(:admin_computer, {})
    end
end

app/controllers/computers_controller.rb
class ComputersController < SystemController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)
    @computer.user = current_user
    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computador cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: "Computador atualizado com sucesso" }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit!
    end
end

app/helpers/admin/computers_helper.rb
module Admin::ComputersHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/admin/computers/_form.html.erb
<%= simple_form_for(@admin_computer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %>
  	<%= f.input :cpu %>
  	<%= f.input :ram %>
  	<%= f.input :brand %>
  	<%= f.input :model %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"Atualizar dados",class: "btn btn-primary btn-xs" %>
  </div>
<% end %>

app/views/admin/computers/edit.html.erb
<div class="intro-lead-in text-muted">
	Editar Computador
</div>

<%= render 'form' %>

<%= link_to 'Show', @admin_computer, class: "btn btn-info btn-xs" %> |
<%= link_to 'Back', admin_computers_path, class: "btn btn-default btn-xs" %>

app/views/admin/computers/index.html.erb
<div class="text-muted intro-lead-in">
    Lista de Computadores
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Usuário</th>
      <th>Nome do Computador</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_computers.each do |admin_computer| %>
      <tr>
        <td> <%= admin_computer.user.name %> </td>
        <td> <%= admin_computer.name %> </td>
        <td>
          <%= link_to 'Mostrar',admin_computer_path(admin_computer), class: "label label-primary" %>
          <%= link_to 'Editar', edit_admin_computer_path(admin_computer), class: "label label-info" %>
          <%= link_to 'Delete', admin_computer, method: :delete, class: "label label-danger", data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/computers/new.html.erb
<h1>New Admin Computer</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_computers_path %>

app/views/admin/computers/show.html.erb
<div class="text-muted intro-lead-in">
	<%= @admin_computer.user.name %>	
</div>

<p>
	<strong>Nome do Computador: </strong> 
	<%= @admin_computer.name %>
</p>

<p>
	<strong>Marca:  </strong>
	<%= @admin_computer.brand %>
</p>

<p>
	<strong>Modelo: </strong>
	<%= @admin_computer.model %>
</p>


<p>
	<strong>CPU: </strong>
	<%= @admin_computer.cpu %>
</p>

<p>
	<strong>MEMORIA RAM: </strong>
	<%= @admin_computer.ram %>
</p>

<p>
	<strong></strong>
</p>



<%= link_to 'Editar', edit_admin_computer_path(@admin_computer), class: "btn btn-info btn-xs" %> |
<%= link_to 'Voltar', admin_computers_path,class: "btn btn-default btn-xs"  %>
<%= link_to 'Deletar', admin_computer_path,method: :delete,data:{confirm: "ESSA AÇÃO NÃO PODE SER DESFEITA!"},class: "btn btn-danger btn-xs"  %>